### ISSUE TITLE
use against kontena kloud masters

### ISSUE THREAD

**Issue by matti** [kontena/terraform-provider-kontena#13]
- https? (`provider.kontena: Invalid config.SSLCertPEM`)
- how does the grid resource work? can not create a grid in kloud. needs a data resource to get the pre-made gri^H^H^Hplatform

**Comment by SpComb** [comment]
> how does the grid resource work? can not create a grid in kloud. needs a data resource to get the pre-made gri^H^H^Hplatform

Hmm... that would probably require the use of [`terraform import kontena_grid.test my-cloud-grid`](https://www.terraform.io/docs/import/usage.html)... I vaugely recall trying to implement that earlier and running into some problems, but I'll have to give it another go.

**Comment by SpComb** [comment]
> https? (provider.kontena: Invalid config.SSLCertPEM)

This is  #16

**Comment by SpComb** [comment]
> > how does the grid resource work? can not create a grid in kloud. needs a data resource to get the pre-made gri^H^H^Hplatform
> 
> Hmm... that would probably require the use of terraform import kontena_grid.test my-cloud-grid... I vaugely recall trying to implement that earlier and running into some problems, but I'll have to give it another go.

Three different approaches for this:

* `provider "kontena_cloud"` with a `resource "kontena_cloud_platform"` that handles the grid
* `resource "kontena_grid"` supporting `terraform import kontena_grid.*`
* `data "kontena_grid"` for read-only access to existing grids

**Comment by matti** [comment]
> provider "kontena_cloud" with a resource "kontena_cloud_platform" that handles the grid

My current understand is that a resource can not represent something that is already existing. If some resource exists outside of terraform state, it needs to be imported.

- data "kontena_grid" for read-only access to existing grids

For kloud grid this is the only real option - Maybe even data "kontena_platform" to represent what it really is (not createable as a resource)

**Comment by SpComb** [comment]
> data "kontena_grid" for read-only access to existing grids
> 
> For kloud grid this is the only real option - Maybe even data "kontena_platform" to represent what it really is (not createable as a resource)

But `data "kontena_grid"` would mean that you would be unable to update e.g. the grid `trusted_subnets`... hence why the `import` might make more sense.

**Comment by matti** [comment]
yes you are right, wasn't thinking that

**Comment by SpComb** [comment]
v0.2 build is out with support for `terraform import`: https://github.com/kontena/terraform-provider-kontena/blob/master/docs/resource_kontena_grid.md#importing
